version: "3"
services:
  xl-deploy-lb:
    image: xebialabsunsupported/haproxy
    container_name: xl-deploy-lb
    depends_on:
      - xl-deploy-master
    ports:
      - "8080:5000"
      - "1936:1936"
    networks:
      - xld-network
    environment:
      BACKENDS: "xl-deploy-master:4516"
      HTTPCHK: "GET /deployit/ha/health"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      COOKIES_PARAMS: "SESSION_XLD prefix"
      LOG_LEVEL: "info"
      TIMEOUT_CONNECT: 60000

  xl-deploy-master:
    image: xebialabs/xl-deploy:10.3
    depends_on:
      - rabbitmq
      - postgresql
    networks:
      - xld-network
    environment:
      - USE_IP_AS_HOSTNAME=true
      - ADMIN_PASSWORD=${XLD_ADMIN_PASS}
      - ACCEPT_EULA=Y
      - XL_CLUSTER_MODE=default
      - XLD_IN_PROCESS=false
      - XLD_TASK_QUEUE_DRIVER_CLASS_NAME=rabbitmq
      - XLD_TASK_QUEUE_URL=amqp://rabbitmq:5672
      - XLD_TASK_QUEUE_USERNAME=rabbitmq
      - XLD_TASK_QUEUE_PASSWORD=${RABBITMQ_PASS}
      - XL_DB_URL=jdbc:postgresql://postgresql:5432/xld-db
      - XL_DB_USERNAME=postgres
      - XL_DB_PASSWORD=${POSTGRES_PASS}
      - FORCE_UPGRADE=true
    volumes:
      - $PWD/xl-deploy-master/conf:/opt/xebialabs/xl-deploy-server/conf # provide deployit-licence.lic file in the conf folder
      - $PWD/xl-deploy-master/centralConfiguration:/opt/xebialabs/xl-deploy-server/centralConfiguration
      - $PWD/xl-deploy-master/plugins:/opt/xebialabs/xl-deploy-server/plugins

  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: rabbitmq
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
      - "15672:15672"
    networks:
      - xld-network
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_LOOPBACK_USERS: none
    volumes:
      - $PWD/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xld-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    command: postgres -c 'max_connections=200'
    networks:
      - xld-network

networks:
  xld-network:
    external: true
